# Generated by Django 4.1.3 on 2023-01-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answer_question_alter_question_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
    ]
