# Generated by Django 4.1.3 on 2023-01-18 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_answer_question_alter_question_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('S', 'SPAM'), ('O', 'OFFENSIVE CONTENT'), ('C', 'CONTAINS PERSONAL INFORMATION'), ('H', 'HARMFUL/THREATENING'), ('X', 'OTHER')], max_length=1)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.set')),
            ],
        ),
    ]
