# Generated by Django 4.1.3 on 2023-01-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_report_author_report_unique_set_author_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('I', 'INACCURATE INFORMATION'), ('A', 'INAPPROPRIATE'), ('C', 'CHEAT'), ('P', 'VIOLATES IP')], max_length=1),
        ),
    ]
