# Generated by Django 3.2.16 on 2023-02-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_imageanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.imageanswer'),
        ),
    ]
