# Generated by Django 3.2.16 on 2023-02-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_answer_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageAnswer',
            new_name='Image',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
