# Generated by Django 3.2.16 on 2023-03-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_set_description_alter_set_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(),
        ),
    ]
