# Generated by Django 3.2.16 on 2023-03-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quiz_performance',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recently_viewed',
            field=models.JSONField(default=dict),
        ),
    ]
