# Generated by Django 3.2.16 on 2023-03-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20230307_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quiz_performance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recently_viewed',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
