# Generated by Django 3.2.16 on 2023-03-10 03:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_profile_recently_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recently_viewed',
            field=models.JSONField(blank=True, default=api.models.getDefaultRecently),
        ),
    ]
