# Generated by Django 3.2.16 on 2023-03-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_image_image'),
        ('api', '0026_alter_profile_user'),
    ]

    operations = [
    ]
