# Generated by Django 3.2.16 on 2023-03-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_set_setlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='set',
            name='setLength',
            field=models.IntegerField(default=0),
        ),
    ]
