# Generated by Django 3.2.16 on 2023-03-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20230322_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lightMode',
            field=models.BooleanField(default=True),
        ),
    ]
